In [1]:
import numpy as np
A = np.array([1, 2, 3, 4])
print(A)

[1 2 3 4]


In [3]:
np.ndim(A)   #배열의 차원수

1

In [4]:
A.shape     #배열의 형상

(4,)

In [5]:
A.shape[0]

4

In [6]:
B = np.array([[1,2], [3,4], [5,6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
np.ndim(B)

2

In [8]:
B.shape

(3, 2)

In [14]:
B.shape[1]

2

In [15]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [16]:
A = np.array([[1,2], [3,4]])
A.shape

(2, 2)

In [18]:
B = np.array([[1,2,3], [4,5,6]])
B.shape

(2, 3)

In [19]:
np.dot(A,B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [20]:
C = np.array([[1,2,3], [1,2,3], [1,2,3]])
C.shape

(3, 3)

In [21]:
np.dot(A,C)

ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)